#!/bin/bash

myhelp() {
    echo "Compile all available NASA benchmarks"
    echo "    -t    testtypes"
    echo "Example: compileAllTests -t \"ep ft bt mg\""
    exit 1
}

#if [[ "$#" -le 1 ]]; then
#    myhelp
#fi
EXTENSIONS=("full" "simple" "fortran" "epio")
SIZES=("S" "W" "A" "B" "C" "D")
TESTS=("bt" "cg" "ep" "ft" "is" "lu" "mg" "sp")
SCRIPT=$@
while [[ $# > 1 ]]
do
key="$1"
case $key in
    -t)
    TESTS=$(echo $2 | tr " " "\n")
    shift # past argument
    ;;
    *)
    echo "Unknown argument encountered : $key . Exit"
    myhelp
            # unknown option
    ;;
esac
shift # past argument or value
done

if hostname | grep wyeasthead ; then
    ssh wyeast01 compileAllTests >|/home/konstan2/wyeast01Comilation &
fi

MAX=128
MIN=1
x=1

cd /smmProject/NPB/NPB3.3-MPI  
make clean
cd bin
rm *
hostname >| compiledby
date >> compiledby
cd ..
for i in ${TESTS[*]}; do
    for j in ${SIZES[*]}; do
        echo "i $i"
        echo "j $j"
        echo "max $MAX"
        while [ $x -le $MAX ]; do
            echo $i $j $x
            echo "making $i NPROCS=$x CLASS=$j"
            if [ $i == "bt" ]; then
                for e in ${EXTENSIONS[*]}; do
                    make $i NPROCS=$x CLASS=$j SUBTYPE=$e
                done
                make $i NPROCS=$x CLASS=$j
            else
                make $i NPROCS=$x CLASS=$j
            fi
            x=$(($x*2))
        done
        x=$MIN
    done
done
cd - 
