#!/bin/bash

if [[ "$#" -ne 3 ]]; then
    echo "Usage: hostfile nproc executable"
else
    #mpirun -oversubscribe --mca btl_tcp_if_include 192.168.1.0/24 -hostfile $1 -n $2 $3
    mpiexec --mca btl_tcp_if_include 192.168.1.0/24 -hostfile $1 -n $2 $3
fi
