#!/bin/bash
if [[ "$#" -ne 2 ]]; then
    echo "Usage: sshrun [ssh compatible command like scp] command"
else
    for i in wyeast{01..17}; do
    echo ""
    echo "******************************************************"
    echo $i
        $1 $i $2
    done
fi
