#!/bin/bash
VERBOSE=false
myhelp() {
    echo "Run some command on all nodes"
    echo "    -t        Type of the command. Example [ssh or scp]"
    echo "    -c        Command.             Example (ps -aux | grep root)"
    echo "    -v        Be verbose.          Optional"
    echo ""
    echo "Usage: sshrun -t [ssh compatible command like scp] -c command <-v>"
    exit 1
}

if [[ "$#" -le 1 ]]; then
    myhelp
fi
SCRIPT=$@
while [[ $# > 1 ]]
do
key="$1"

case $key in
    -t)
    TYPE="$2"
    shift # past argument
    ;;
    -c)
    COMMAND="$2"
    echo $COMMAND
    shift # past argument
    ;;
    -v)
    VERBOSE=true
    echo $VERBOSE
    ;;
    *)
    echo "Unknown argument encountered : $key . Exit"
    myhelp
    exit
            # unknown option
    ;;
esac
shift # past argument or value
done

for node in wyeast{01..17}; do
    if [ "$VERBOSE" ==  true ]; then
        echo ""
        echo "******************************************************"
        echo $node
    fi
    $TYPE $node $COMMAND
done
