#!/bin/bash

EXT=""

myhelp() {
    echo "testRunner ERROR: expected 5 arguments, got $#" 
    echo "$1"
    echo "$2"
    echo "$3"
    echo "$4"
    echo "$5"
    echo "$6"
    echo "Usage: testype hostfile worldsize nproc procs_per_node"
    echo ""
    echo "example: ep /smmProject/hosts S 4 1"
    exit 1
}

if [[ "$#" -le 1 ]]; then
    myhelp
fi
SCRIPT=$@
while [[ $# > 1 ]]
do
key="$1"

case $key in
    --testtype)
    TESTNAME=$2
    shift # past argument
    ;;
    --hfile)
    HOSTFILE="$2"
    shift # past argument
    ;;
    --worldsize)
    WORLDSIZE="$2"
    shift # past argument
    ;;
    --nprocs)
    NPROC="$2"
    shift # past argument
    ;;
    --nprocspernode)
    NPROCSPERNODE="$2"
    shift # past argument
    ;;
    --ext)
    EXT=".$2"
    shift # past argument
    ;;
    --smitype)
    SMITYPE="$2"
    echo "Setting smitype $SMITYPE"
    shift # past argument
    ;;
    -h|--help)
    echo "HELP"
    myhelp
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
    echo "Unknown argument encountered : $key . Exit"
    myhelp
            # unknown option
    ;;
esac
shift # past argument or value
done

if [ $TESTNAME == "bt" ]; then
    EXT=".mpi_io_full"
else
    EXT=""
fi

Color_OFF="[0m"
Color1="[31m"
Color5="[35m"
sleep 2s
#binary path is hardcoded, sorry
BINPATH='/smmProject/NPB/NPB3.3-MPI/bin/'

FNAME="$TESTNAME.$WORLDSIZE.$NPROC$EXT"
#RESULTDIR="/smmProject/results/$TESTNAME/$WORLDSIZE/$NPROC"
#RESULTSLOC="/smmProject/results/$TESTNAME/$WORLDSIZE/$NPROC"
RESULTDIR="/smmProject/results/$TESTNAME"
RESULTSLOC="/smmProject/results/$TESTNAME"
echo "ResultDir $RESULTDIR"
echo `test -d $RESULTDIR`

if [ ! -d $RESULTDIR ]; then
     mkdir -p $RESULTDIR
fi
TESTPATH="$BINPATH$FNAME"
if [ -e $TESTPATH ]; then
    EPOCHTIME=`date +%s`
    DESTINATIONFILE="$RESULTDIR/$EPOCHTIME"

    echo "$Color5"
    echo "     ###############################################"
    echo "     ############### TEST RUN INFO #################"
    echo "     ###############################################"
    echo ""
    echo ""
    echo "Executable               : $TESTPATH"
    echo "Results will be saved in : $DESTINATIONFILE"
    echo "SMICOUNT                 : $SMITYPE"
    echo "$ColorOFF"
    echo "$Color1 Warning: SMI RESULTS ARE IGNORED TO CHANGE EDIT /smmProject/utilities/testRunner $Color_OFF"

#    mpiBasic $HOSTFILE $NPROC $TESTPATH 
#    echo "proc per node    =  $NPROCSPERNODE"
#    echo "smi count        =   0"
#    echo "smi size         =   0"
#    echo "smi frequency    =   0"

    mpiBasic $HOSTFILE $NPROC $TESTPATH &> $DESTINATIONFILE
    echo "procs per node    =  $NPROCSPERNODE" >> $DESTINATIONFILE

    #This must be change to fetching actual information
    echo "smi count        =   0" >> $DESTINATIONFILE
    echo "smi size         =   $SMITYPE" >> $DESTINATIONFILE
    echo "smi frequency    =   0" >> $DESTINATIONFILE
    
    echo "$Color5"
    echo "CURRENT TEST COMPLETED"
    echo ""
    echo "$ColorOFF"
else
    echo "ERROR file $TESTPATH doesnt exits"
    exit 111
fi
