#!/bin/bash

if [[ "$#" -ne 4 ]]; then
    echo "Usage: testype hostfile worldsize nproc"
    echo ""
    echo "example: ep /smmProject/hosts S 4"
else
    TESTNAME=$1
    HOSTFILE=$2 
    WORLDSIZE=$3
    NPROC=$4
    #binary path is hardcoded, sorry
    BINPATH='/smmProject/NPB3/NPB3.3-MPI/bin/'
    
    FNAME="$TESTNAME.$WORLDSIZE.$NPROC"
    #RESULTDIR="/smmProject/results/$TESTNAME/$WORLDSIZE/$NPROC"
    #RESULTSLOC="/smmProject/results/$TESTNAME/$WORLDSIZE/$NPROC"
    RESULTDIR="/smmProject/results/$TESTNAME"
    RESULTSLOC="/smmProject/results/$TESTNAME"
    echo "ResultDir $RESULTDIR"
    echo `test -d $RESULTDIR`

    if [ ! -d $RESULTDIR ]; then
         mkdir -p $RESULTDIR
    fi
    TESTPATH="$BINPATH$FNAME"

    EPOCHTIME=`date +%s`
    DESTINATIONFILE="$RESULTDIR/$EPOCHTIME"

    echo "destination file $DESTINATIONFILE"

    mpiBasic $HOSTFILE $NPROC $TESTPATH &> $DESTINATIONFILE
    #mpiBasic $HOSTFILE $NPROC $TESTPATH
fi
