#!/bin/bash

if [[ "$#" -ne 5 ]] && [[ "$#" -ne 6 ]]; then
    echo "testRunner ERROR: expected 5 arguments, got $#" 
    echo "$1"
    echo "$2"
    echo "$3"
    echo "$4"
    echo "$5"
    echo "$6"
    echo "Usage: testype hostfile worldsize nproc procs_per_node"
    echo ""
    echo "example: ep /smmProject/hosts S 4 1"
    exit 1
fi

if [[ "$#" -eq 6 ]]; then
    EXT=".$6"
else 
    EXT=""
fi

Color_OFF="[0m"
Color1="[31m"
Color5="[35m"
sleep 2s
TESTNAME=$1
HOSTFILE=$2
WORLDSIZE=$3
NPROC=$4
#binary path is hardcoded, sorry
BINPATH='/smmProject/NPB/NPB3.3-MPI/bin/'

FNAME="$TESTNAME.$WORLDSIZE.$NPROC$EXT"
#RESULTDIR="/smmProject/results/$TESTNAME/$WORLDSIZE/$NPROC"
#RESULTSLOC="/smmProject/results/$TESTNAME/$WORLDSIZE/$NPROC"
RESULTDIR="/smmProject/results/$TESTNAME"
RESULTSLOC="/smmProject/results/$TESTNAME"
echo "ResultDir $RESULTDIR"
echo `test -d $RESULTDIR`

if [ ! -d $RESULTDIR ]; then
     mkdir -p $RESULTDIR
fi
TESTPATH="$BINPATH$FNAME"
if [ -e $TESTPATH ]; then
    EPOCHTIME=`date +%s`
    DESTINATIONFILE="$RESULTDIR/$EPOCHTIME"

    echo "$Color5"
    echo "     ###############################################"
    echo "     ############### TEST RUN INFO #################"
    echo "     ###############################################"
    echo ""
    echo ""
    echo "Executable               : $TESTPATH"
    echo "Results will be saved in : $DESTINATIONFILE"
    echo "$ColorOFF"
    echo "$Color1 Warning: SMI RESULTS ARE IGNORED TO CHANGE EDIT /smmProject/utilities/testRunner $Color_OFF"

#    mpiBasic $HOSTFILE $NPROC $TESTPATH 
#    echo "proc per node    =  $5"
#    echo "smi count        =   0"
#    echo "smi size         =   0"
#    echo "smi frequency    =   0"

    mpiBasic $HOSTFILE $NPROC $TESTPATH &> $DESTINATIONFILE
    echo "proc per node    =  $5" >> $DESTINATIONFILE

    #This must be change to fetching actual information
    echo "smi count        =   0" >> $DESTINATIONFILE
    echo "smi size         =   0" >> $DESTINATIONFILE
    echo "smi frequency    =   0" >> $DESTINATIONFILE
    
    echo "$Color5"
    echo "CURRENT TEST COMPLETED"
    echo ""
    echo "$ColorOFF"
else
    echo "ERROR file $TESTPATH doesnt exits"
    exit 111
fi
