#!/bin/bash

resetGroup
cd /smmProject
for i in wyeast{01..17}; do

    echo "Updating $i"
    sudo rsync -rva --exclude results --exclude /smmProject/NPB/NPB3.3-MPI/bin . $i:/smmProject &
    echo ""
    echo ""

done
